### ISSUE TITLE
My TODO list

### ISSUE THREAD

**Issue by Xvezda** [Xvezda/xvezda.github.io#2]
- [ ] Learn golang
- [ ] Learn Rust
- [ ] Learn Ruby
- [ ] Learn REACT
- [ ] Learn MongoDB
- [ ] Review Swift
- [ ] Upload write-ups
- [ ] Building my own wargame website
- [ ] Build my own library

**Comment by Xvezda** [comment]
https://tour.golang.org/welcome/1

**Comment by Xvezda** [comment]
Move to https://notion.so
